/**
 * Every spelling of a club or player that a Tenaball source uses, tied to one
 * identity. Sources are matched against these exactly after normalising; a
 * name that is not here stops its question instead of being guessed at.
 *
 * `names` are spellings found in the sources, and in our own database, and are
 * also accepted as answers. `extra` are what people type that no source uses.
 */
export interface Entity {
  id: string
  label: string
  names: string[]
  extra?: string[]
}

const club = (id: string, label: string, names: string[] = [], extra: string[] = []): Entity =>
  ({ id, label, names, extra })

export const CLUBS: Entity[] = [
  // Ísland
  club('kr', 'KR', [], ['Knattspyrnufélag Reykjavíkur']),
  club('valur', 'Valur'),
  club('fram', 'Fram'),
  club('ia', 'ÍA', [], ['Akranes', 'Skaginn']),
  club('fh', 'FH', [], ['Fimleikafélag Hafnarfjarðar']),
  club('vikingur', 'Víkingur R.', ['Víkingur', 'Víkingur Reykjavík'], ['Víkingur Reykjavik']),
  club('vikingur-o', 'Víkingur Ó.', ['Víkingur Ólafsvík', 'Víkingur Ó']),
  club('keflavik', 'Keflavík'),
  club('ibv', 'ÍBV', [], ['Eyjamenn']),
  club('breidablik', 'Breiðablik', [], ['Blikar']),
  club('ka', 'KA'),
  club('thor', 'Þór', ['Þór Akureyri', 'Þór Ak.', 'Þór A.'], ['Thor']),
  club('iba', 'ÍBA', ['ÍB Akureyri'], ['Íþróttabandalag Akureyrar']),
  club('stjarnan', 'Stjarnan'),
  club('fylkir', 'Fylkir'),
  club('hk', 'HK'),
  club('vestri', 'Vestri'),
  club('afturelding', 'Afturelding'),
  club('grindavik', 'Grindavík'),
  club('fjolnir', 'Fjölnir'),
  club('throttur', 'Þróttur R.', ['Þróttur', 'Þróttur Reykjavík']),
  club('leiknir', 'Leiknir R.', ['Leiknir', 'Leiknir Reykjavík']),
  club('grotta', 'Grótta'),

  // England
  club('arsenal', 'Arsenal'),
  club('astonvilla', 'Aston Villa', [], ['Villa', 'Aston Villa FC']),
  club('bournemouth', 'Bournemouth', [], ['AFC Bournemouth']),
  club('brentford', 'Brentford'),
  club('brighton', 'Brighton & Hove Albion', ['Brighton'], ['Brighton and Hove Albion']),
  club('burnley', 'Burnley'),
  club('chelsea', 'Chelsea', ['Chelsea FC', 'Chelsea F.C.']),
  club('palace', 'Crystal Palace', [], ['Palace']),
  club('everton', 'Everton'),
  club('fulham', 'Fulham'),
  club('ipswich', 'Ipswich Town', ['Ipswich', 'Ipswich Town F.C.']),
  club('leicester', 'Leicester City', ['Leicester']),
  club('liverpool', 'Liverpool', ['Liverpool FC']),
  club('luton', 'Luton Town', ['Luton']),
  club('mancity', 'Manchester City', ['Man City'], ['MCFC']),
  club('manutd', 'Manchester United', ['Man United'], ['Man Utd']),
  club('newcastle', 'Newcastle United', ['Newcastle']),
  club('forest', 'Nottingham Forest', ["Nott'm Forest"], ['Forest']),
  club('sheffutd', 'Sheffield United', [], ['Sheffield Utd']),
  club('southampton', 'Southampton'),
  club('tottenham', 'Tottenham Hotspur', ['Tottenham'], ['Spurs']),
  club('westham', 'West Ham United', ['West Ham']),
  club('wolves', 'Wolverhampton Wanderers', ['Wolves']),
  club('leeds', 'Leeds United', ['Leeds']),
  club('sunderland', 'Sunderland'),
  club('birmingham', 'Birmingham City', ['Birmingham']),
  club('blackburn', 'Blackburn Rovers', ['Blackburn']),
  club('bolton', 'Bolton Wanderers', ['Bolton']),
  club('hull', 'Hull City', ['Hull']),
  club('portsmouth', 'Portsmouth'),
  club('stoke', 'Stoke City', ['Stoke']),
  club('wigan', 'Wigan Athletic', ['Wigan']),
  club('coventry', 'Coventry City', ['Coventry']),
  club('watford', 'Watford'),
  club('westbrom', 'West Bromwich Albion', ['West Brom'], ['WBA']),
  club('swansea', 'Swansea City', ['Swansea']),
  club('huddersfield', 'Huddersfield Town', ['Huddersfield']),
  club('cardiff', 'Cardiff City', ['Cardiff']),
  club('norwich', 'Norwich City', ['Norwich']),
  club('middlesbrough', 'Middlesbrough'),
  club('bristolcity', 'Bristol City'),
  club('millwall', 'Millwall'),
  club('preston', 'Preston North End', ['Preston']),
  club('derby', 'Derby County', ['Derby']),
  club('qpr', 'Queens Park Rangers', ['QPR']),
  club('sheffwed', 'Sheffield Wednesday', ['Sheffield Weds']),
  club('oxford', 'Oxford United', ['Oxford']),
  club('plymouth', 'Plymouth Argyle', ['Plymouth']),
  club('wrexham', 'Wrexham'),
  club('charlton', 'Charlton Athletic', ['Charlton']),

  // Spánn
  club('realmadrid', 'Real Madrid'),
  club('barcelona', 'Barcelona', ['FC Barcelona'], ['Barça']),
  club('atletico', 'Atlético Madrid', ['Ath Madrid'], ['Atlético']),
  club('athletic', 'Athletic Bilbao', ['Ath Bilbao', 'Athletic Club'], ['Bilbao']),
  club('sevilla', 'Sevilla', ['Sevilla FC']),
  club('villarreal', 'Villarreal', ['Villarreal CF', 'Villareal CF']),
  club('valencia', 'Valencia', ['Valencia CF']),
  club('betis', 'Real Betis', ['Betis']),
  club('sociedad', 'Real Sociedad', ['Sociedad']),
  club('celta', 'Celta Vigo', ['Celta']),
  club('rayo', 'Rayo Vallecano', ['Vallecano'], ['Rayo']),
  club('osasuna', 'Osasuna', ['CA Osasuna']),
  club('mallorca', 'Mallorca', ['RCD Mallorca']),
  club('getafe', 'Getafe'),
  club('espanyol', 'Espanyol', ['Espanol', 'RCD Espanyol']),
  club('girona', 'Girona'),
  club('alaves', 'Alavés', ['Deportivo Alavés']),
  club('elche', 'Elche'),
  club('levante', 'Levante'),
  club('oviedo', 'Real Oviedo', ['Oviedo']),

  // Ítalía
  club('milan', 'AC Milan', ['Milan']),
  club('inter', 'Inter', ['Inter Milan'], ['Internazionale', 'Inter Mílanó']),
  club('juventus', 'Juventus'),
  club('napoli', 'Napoli', ['SSC Napoli']),
  club('atalanta', 'Atalanta', ['Atalanta BC']),
  club('roma', 'Roma', ['AS Roma', 'A.S. Roma']),
  club('lazio', 'Lazio', ['SS Lazio', 'S. S. Lazio']),
  club('fiorentina', 'Fiorentina', ['ACF Fiorentina']),
  club('bologna', 'Bologna'),
  club('como', 'Como', ['Como 1907']),
  club('torino', 'Torino', ['Torino FC', 'Torino F.C.']),
  club('parma', 'Parma', ['Parma Calcio 1913']),
  club('udinese', 'Udinese'),
  club('genoa', 'Genoa'),
  club('cagliari', 'Cagliari'),
  club('verona', 'Hellas Verona', ['Verona']),
  club('lecce', 'Lecce'),
  club('sassuolo', 'Sassuolo'),
  club('cremonese', 'Cremonese'),
  club('pisa', 'Pisa'),

  // Þýskaland
  club('bayern', 'Bayern München', ['Bayern Munich', 'FC Bayern München'], ['Bayern', 'FC Bayern']),
  club('dortmund', 'Borussia Dortmund', ['Dortmund'], ['BVB']),
  club('leverkusen', 'Bayer Leverkusen', ['Leverkusen'], ['Bayer 04 Leverkusen']),
  club('frankfurt', 'Eintracht Frankfurt', ['Frankfurt', 'Ein Frankfurt'], ['Eintracht']),
  club('leipzig', 'RB Leipzig', [], ['Leipzig']),
  club('stuttgart', 'VfB Stuttgart', ['Stuttgart']),
  club('freiburg', 'SC Freiburg', ['Freiburg']),
  club('mainz', 'Mainz 05', ['Mainz', '1. FSV Mainz 05']),
  club('gladbach', 'Borussia Mönchengladbach', ['Mönchengladbach', "M'gladbach"], ['Gladbach']),
  club('wolfsburg', 'VfL Wolfsburg', ['Wolfsburg']),
  club('bremen', 'Werder Bremen', [], ['Bremen']),
  club('augsburg', 'FC Augsburg', ['Augsburg']),
  club('union', 'Union Berlin', ['1. FC Union Berlin']),
  club('hoffenheim', 'Hoffenheim', ['TSG Hoffenheim', '1899 Hoffenheim']),
  club('heidenheim', 'Heidenheim', ['1. FC Heidenheim']),
  club('stpauli', 'St. Pauli', ['FC St. Pauli']),
  club('koln', '1. FC Köln', ['FC Koln', 'Köln'], ['Koln', 'Cologne']),
  club('hamburg', 'Hamburger SV', ['Hamburg'], ['HSV']),
  club('schalke', 'Schalke 04', ['FC Schalke 04'], ['Schalke']),

  // Frakkland
  club('psg', 'Paris Saint-Germain', ['Paris SG'], ['PSG']),
  club('marseille', 'Marseille', ['Olympique de Marseille'], ['OM']),
  club('monaco', 'Monaco', ['AS Monaco']),
  club('lille', 'Lille', ['LOSC Lille']),
  club('lyon', 'Lyon', ['Olympique Lyonnais']),
  club('nice', 'Nice', ['OGC Nice']),
  club('lens', 'Lens', ['RC Lens']),
  club('strasbourg', 'Strasbourg', ['RC Strasbourg Alsace']),
  club('brest', 'Brest', ['Stade Brestois 29']),
  club('rennes', 'Rennes', ['Stade Rennais']),
  club('toulouse', 'Toulouse', ['Toulouse FC']),
  club('auxerre', 'Auxerre'),
  club('nantes', 'Nantes'),
  club('angers', 'Angers'),
  club('lehavre', 'Le Havre'),
  club('lorient', 'Lorient'),
  club('metz', 'Metz'),
  club('parisfc', 'Paris FC'),
  club('reims', 'Reims', ['Stade de Reims']),
  club('clermont', 'Clermont', ['Clermont Foot']),
  club('montpellier', 'Montpellier', ['Montpellier HSC']),

  // Evrópa annars staðar
  club('ajax', 'Ajax', ['Ajax Amsterdam', 'Ajax FC']),
  club('benfica', 'Benfica'),
  club('porto', 'Porto', ['FC Porto']),
  club('celtic', 'Celtic', ['Glasgow Celtic'], ['Celtic FC']),
  club('feyenoord', 'Feyenoord', [], ['Feyenoord Rotterdam']),
  club('psv', 'PSV Eindhoven', [], ['PSV']),
  club('redstar', 'Rauða stjarnan', ['Red Star Belgrade', 'Rauða stjarnan Belgrad'], ['Crvena zvezda']),
  club('steaua', 'Steaua Búkarest', ['FCSB', 'Steaua București', 'Steaua Bucharest'], ['Steaua']),
  club('goteborg', 'IFK Göteborg', [], ['Göteborg', 'Gautaborg']),
  club('anderlecht', 'Anderlecht', ['RSC Anderlecht']),
  club('galatasaray', 'Galatasaray'),
  club('cska', 'CSKA Moskva', ['CSKA Moscow'], ['CSKA']),
  club('zenit', 'Zenit Pétursborg', ['Zenit Saint Petersburg', 'Zenit Sankti Pétursborg'], ['Zenit']),
  club('shakhtar', 'Shakhtar Donetsk', ['Shaktar Donetsk'], ['Shakhtar']),
  // Holland
  club('az', 'AZ Alkmaar', ['AZ']),
  club('twente', 'Twente', ['FC Twente']),
  club('utrecht', 'Utrecht', ['FC Utrecht']),
  club('groningen', 'Groningen', ['FC Groningen']),
  club('heerenveen', 'Heerenveen', ['SC Heerenveen']),
  club('heracles', 'Heracles', ['Heracles Almelo']),
  club('spartarotterdam', 'Sparta Rotterdam'),
  club('vitesse', 'Vitesse', ['Vitesse Arnhem']),
  club('willem2', 'Willem II'),
  club('zwolle', 'PEC Zwolle', ['Zwolle']),
  club('waalwijk', 'RKC Waalwijk', ['Waalwijk']),
  // our own feed writes Fortuna Sittard without the second letter of its name
  club('fortunasittard', 'Fortuna Sittard', ['For Sittard']),
  club('adodenhaag', 'ADO Den Haag', ['Den Haag']),
  club('emmen', 'FC Emmen', ['Emmen']),
  club('vvvvenlo', 'VVV-Venlo', ['VVV Venlo']),
  club('nec', 'NEC Nijmegen', ['NEC', 'Nijmegen']),
  club('goahead', 'Go Ahead Eagles'),
  club('excelsior', 'Excelsior', ['SBV Excelsior']),
  club('volendam', 'Volendam', ['FC Volendam']),
  club('cambuur', 'Cambuur', ['SC Cambuur']),
  club('nacbreda', 'NAC Breda'),
  club('almerecity', 'Almere City'),
  club('telstar', 'Telstar', ['SC Telstar']),

  // Portúgal
  club('sporting', 'Sporting', ['Sporting CP', 'Sporting Lisbon', 'Sp Lisbon'], ['Sporting Lissabon']),
  club('braga', 'Braga', ['SC Braga', 'Sporting Braga', 'Sp Braga']),
  club('vitoriaguimaraes', 'Vitória Guimarães', ['Vitória de Guimarães', 'Vitoria Guimaraes', 'Guimaraes'], ['Guimarães']),
  club('famalicao', 'Famalicão', ['FC Famalicão']),
  club('rioave', 'Rio Ave'),
  club('estoril', 'Estoril', ['Estoril Praia']),
  club('gilvicente', 'Gil Vicente'),
  club('casapia', 'Casa Pia'),
  club('arouca', 'Arouca', ['FC Arouca']),
  club('moreirense', 'Moreirense'),
  club('santaclara', 'Santa Clara', ['CD Santa Clara']),
  club('nacional', 'Nacional', ['CD Nacional']),
  club('tondela', 'Tondela', ['CD Tondela']),
  club('avs', 'AVS'),
  club('estrela', 'Estrela da Amadora', ['Estrela']),
  club('alverca', 'Alverca', ['FC Alverca']),
  club('academicoviseu', 'Académico de Viseu', ['Academico de Viseu', 'Academico Viseu']),
  club('boavista', 'Boavista'),
  club('chaves', 'Chaves', ['GD Chaves']),
  club('farense', 'Farense', ['SC Farense']),
  club('maritimo', 'Marítimo', ['Maritimo']),
  club('portimonense', 'Portimonense'),
  club('vizela', 'Vizela', ['FC Vizela']),

  // fleiri félög úr eldri tímabilum
  club('frosinone', 'Frosinone'),
  club('sampdoria', 'Sampdoria', ['UC Sampdoria']),
  club('monza', 'Monza', ['AC Monza']),
  club('venezia', 'Venezia', ['Venezia FC']),
  club('granada', 'Granada', ['Granada CF']),
  club('bielefeld', 'Arminia Bielefeld', ['Bielefeld']),
  club('hertha', 'Hertha Berlín', ['Hertha', 'Hertha BSC', 'Hertha Berlin']),
  club('reading', 'Reading'),
  club('barnsley', 'Barnsley'),
  club('rotherham', 'Rotherham', ['Rotherham United']),
  club('wycombe', 'Wycombe', ['Wycombe Wanderers']),
  club('lincolncity', 'Lincoln City', ['Lincoln']),

  // eldri tímabil: nöfnin eins og okkar eigin gagnasafn skrifar þau
  club('degraafschap', 'De Graafschap'),
  club('roda', 'Roda JC', ['Roda']),
  club('hannover', 'Hannover 96', ['Hannover']),
  club('kaiserslautern', 'Kaiserslautern', ['1. FC Kaiserslautern']),
  club('nurnberg', 'Nürnberg', ['Nurnberg', '1. FC Nürnberg']),
  club('almeria', 'Almería', ['Almeria', 'UD Almería']),
  club('hercules', 'Hércules', ['Hercules']),
  club('deportivo', 'Deportivo La Coruña', ['La Coruna', 'Deportivo de La Coruña', 'Deportivo A Coruña'], ['Deportivo']),
  club('malaga', 'Málaga', ['Malaga', 'Málaga CF']),
  club('racingsantander', 'Racing Santander', ['Santander']),
  club('sportinggijon', 'Sporting Gijón', ['Sp Gijon', 'Sporting Gijon']),
  club('zaragoza', 'Zaragoza', ['Real Zaragoza']),
  club('nancy', 'Nancy', ['AS Nancy']),
  club('elversberg', 'SV Elversberg', ['Elversberg']),
  club('lemans', 'Le Mans'),
  club('troyes', 'Troyes', ['ESTAC Troyes']),
  club('torreense', 'Torreense', ['SC Torreense']),
  club('paderborn', 'Paderborn', ['SC Paderborn']),
]

const person = (id: string, label: string, names: string[] = [], extra: string[] = []): Entity =>
  ({ id, label, names, extra })

export const PEOPLE: Entity[] = [
  // Besta deild
  person('gardar-gunnlaugsson', 'Garðar Gunnlaugsson'),
  person('andri-runar-bjarnason', 'Andri Rúnar Bjarnason'),
  person('patrick-pedersen', 'Patrick Pedersen', ['Patrik Pedersen']),
  person('gary-martin', 'Gary Martin'),
  person('steven-lennon', 'Steven Lennon'),
  person('nikolaj-hansen', 'Nikolaj Hansen'),
  person('nokkvi-thorisson', 'Nökkvi Þeyr Þórisson', ['Nökkvi Þórisson']),
  person('gudmundur-magnusson', 'Guðmundur Magnússon'),
  person('emil-atlason', 'Emil Atlason'),
  person('benony-andresson', 'Benoný Breki Andrésson'),

  // Premier League - FPL spells some players out in full
  person('haaland', 'Erling Haaland', [], ['Erling Braut Haaland']),
  person('palmer', 'Cole Palmer'),
  person('isak', 'Alexander Isak'),
  person('foden', 'Phil Foden'),
  person('solanke', 'Dominic Solanke'),
  person('watkins', 'Ollie Watkins'),
  person('salah', 'Mohamed Salah', [], ['Mo Salah']),
  person('son', 'Son Heung-min', ['Heung-Min Son'], ['Son']),
  person('bowen', 'Jarrod Bowen'),
  person('mateta', 'Jean-Philippe Mateta'),
  person('saka', 'Bukayo Saka'),
  person('mbeumo', 'Bryan Mbeumo'),
  person('wood', 'Chris Wood'),
  person('wissa', 'Yoane Wissa'),
  person('cunha', 'Matheus Cunha', ['Matheus Santos Carneiro Da Cunha']),
  person('strand-larsen', 'Jørgen Strand Larsen', [], ['Strand Larsen']),
  person('igor-thiago', 'Igor Thiago', ['Igor Thiago Nascimento Rodrigues']),
  person('semenyo', 'Antoine Semenyo'),
  person('gibbs-white', 'Morgan Gibbs-White'),
  person('joao-pedro', 'João Pedro', ['João Pedro Junqueira de Jesus']),
  person('calvert-lewin', 'Dominic Calvert-Lewin'),
  person('gyokeres', 'Viktor Gyökeres'),
  person('kroupi', 'Eli Junior Kroupi', ['Junior Kroupi']),
  person('welbeck', 'Danny Welbeck'),
  person('lukaku', 'Romelu Lukaku'),
  person('sanchez', 'Alexis Sánchez'),
  person('aguero', 'Sergio Agüero'),
  person('diego-costa', 'Diego Costa', ['Diego Da Silva Costa']),
  person('alli', 'Dele Alli', ['Bamidele Alli']),
  person('ibrahimovic', 'Zlatan Ibrahimović', [], ['Zlatan']),
  person('hazard', 'Eden Hazard'),
  person('king', 'Joshua King', [], ['Josh King']),
  person('benteke', 'Christian Benteke'),
  person('defoe', 'Jermain Defoe'),
  person('llorente', 'Fernando Llorente'),
  person('vardy', 'Jamie Vardy'),
  person('sterling', 'Raheem Sterling'),
  person('firmino', 'Roberto Firmino'),
  person('lacazette', 'Alexandre Lacazette'),
  person('gabriel-jesus', 'Gabriel Jesus', ['Gabriel Fernando de Jesus']),
  person('mahrez', 'Riyad Mahrez'),
  person('murray', 'Glenn Murray'),
  person('aubameyang', 'Pierre-Emerick Aubameyang', [], ['Auba']),
  person('mane', 'Sadio Mané'),
  person('callum-wilson', 'Callum Wilson'),
  person('jimenez', 'Raúl Jiménez'),
  person('pogba', 'Paul Pogba'),
  person('richarlison', 'Richarlison', ['Richarlison de Andrade']),
  person('gylfi', 'Gylfi Sigurðsson', ['Gylfi Þór Sigurðsson'], ['Gylfi']),
  person('ings', 'Danny Ings'),
  person('martial', 'Anthony Martial'),
  person('rashford', 'Marcus Rashford'),
  person('bruno-fernandes', 'Bruno Fernandes', ['Bruno Miguel Borges Fernandes']),
  person('bamford', 'Patrick Bamford'),
  person('gundogan', 'İlkay Gündoğan', ['Ilkay Gündogan']),
  person('de-bruyne', 'Kevin De Bruyne', [], ['KDB']),
  person('jota', 'Diogo Jota'),
  person('zaha', 'Wilfried Zaha'),
  person('toney', 'Ivan Toney'),
  person('martinelli', 'Gabriel Martinelli', ['Gabriel Martinelli Silva']),
  person('odegaard', 'Martin Ødegaard'),
  person('mitrovic', 'Aleksandar Mitrović'),

  // Meistaradeildin
  person('ronaldo', 'Cristiano Ronaldo', ['Cristiano Ronaldo dos Santos Aveiro'], ['CR7']),
  person('messi', 'Lionel Messi'),
  person('lewandowski', 'Robert Lewandowski'),
  person('benzema', 'Karim Benzema'),
  person('mbappe', 'Kylian Mbappé'),
  person('raul', 'Raúl', [], ['Raúl González']),
  person('muller', 'Thomas Müller'),
  person('van-nistelrooy', 'Ruud van Nistelrooy', [], ['Van Nistelrooy']),
  person('kane', 'Harry Kane'),
  person('henry', 'Thierry Henry'),

  // A-landslið karla: Wikipedia skrifar íslensku stafina, Transfermarkt ekki
  person('birkir-bjarnason', 'Birkir Bjarnason', ['Birkir Már Bjarnason'], ['Birkir']),
  person('aron-gunnarsson', 'Aron Gunnarsson', ['Aron Einar Gunnarsson'], ['Aron']),
  person('runar-kristinsson', 'Rúnar Kristinsson', ['Runar Kristinsson']),
  person('birkir-mar-saevarsson', 'Birkir Már Sævarsson', ['Birkir Már Saevarsson', 'Birkir Mar Saevarsson']),
  person('johann-berg', 'Jóhann Berg Guðmundsson', ['Jóhann Berg Gudmundsson', 'Johann Berg Gudmundsson'], ['Jóhann Berg']),
  person('ragnar-sigurdsson', 'Ragnar Sigurðsson', ['Ragnar Sigurdsson']),
  person('kari-arnason', 'Kári Árnason', ['Kari Arnason']),
  person('hermann-hreidarsson', 'Hermann Hreiðarsson', ['Hermann Hreidarsson'], ['Hermann']),
  person('eidur', 'Eiður Guðjohnsen', ['Eidur Gudjohnsen', 'Eiður Smári Guðjohnsen'], ['Eiður', 'Eiður Smári']),

  // Gullknötturinn 1990-2009: íslenska Wikipedia umritar mörg nöfnin
  person('matthaus', 'Lothar Matthäus', ['Lothar Matthaus']),
  person('papin', 'Jean-Pierre Papin'),
  person('van-basten', 'Marco van Basten', [], ['Van Basten']),
  person('baggio', 'Roberto Baggio'),
  person('stoichkov', 'Hristo Stoichkov', ['Hristo Stoitsjkov']),
  person('weah', 'George Weah'),
  person('sammer', 'Matthias Sammer'),
  person('ronaldo-nazario', 'Ronaldo', ['Ronaldo Luís Nazário de Lima'], ['Ronaldo Nazário', 'Ronaldo Nazario', 'R9']),
  person('zidane', 'Zinedine Zidane', [], ['Zizou']),
  person('rivaldo', 'Rivaldo'),
  person('figo', 'Luís Figo', ['Luis Figo']),
  person('owen', 'Michael Owen'),
  person('nedved', 'Pavel Nedvěd', ['Pavel Nedved']),
  person('shevchenko', 'Andriy Shevchenko', ['Andrei Sjevtsjenko', 'Andrij Sjevtsjenko'], ['Sjevtsjenko']),
  person('ronaldinho', 'Ronaldinho'),
  person('cannavaro', 'Fabio Cannavaro'),
  person('kaka', 'Kaká', ['Kaka']),
]
